apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap14-gitnodeart-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap14-gitnodeart-test 
  name: rhtap14-gitnodeart-test
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rhtap14-gitnodeart-test 
